// <auto-generated />
namespace R61M6C2_w01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(name));
        
        string IMigrationMetadata.Id
        {
            get { return "202412030400537_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
